#Configuration file for Beckhoff EL4134
vendor_id: 0x00000002
product_id: 0x10263052
rpdo:  # RxPDO
  - index: 0x1600
    channels:
      - {index: 0x7000, sub_index: 1, type: int16, command_interface: effort.1, factor: 3276.7}
  - index: 0x1601
    channels:
      - {index: 0x7010, sub_index: 1, type: int16, command_interface: effort.2, factor: 3276.7}
  - index: 0x1602
    channels:
      - {index: 0x7020, sub_index: 1, type: int16, command_interface: enable, factor: 3276.7}
  - index: 0x1603
    channels:
      - {index: 0x7030, sub_index: 1, type: int16, command_interface: analog_output.4, factor: 3276.7}

sm:  # Sync Manager
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}  