controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pant_position_controller:
      type: pant_position_controller/PantPositionController

pant_position_controller:
  ros__parameters:
    command_interfaces:
      - position
      - effort.1
      - effort.2
      - enable
    state_interfaces:
      - position
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    effort_limits: 2.0
